#!/usr/bin/env node

/**
 * OpenMind AI - Enhanced Secret Management
 * Loads secrets from .env and manages them securely
 */

const fs = require('fs').promises;
const path = require('path');
const crypto = require('crypto');
const dotenv = require('dotenv');

class SecretManager {
  constructor() {
    this.projectRoot = path.resolve(__dirname, '..');
    this.envPath = path.join(this.projectRoot, '.env');
    this.secretsDir = path.join(this.projectRoot, 'secrets');
    this.config = {};
  }

  async initialize() {
    console.log('🔐 Initializing Secret Management System...');

    // Load existing .env file
    await this.loadEnvFile();

    // Ensure secrets directory exists
    await this.ensureSecretsDirectory();

    // Validate and generate missing secrets
    await this.validateAndGenerateSecrets();

    // Create .env file with safe defaults
    await this.createSafeEnvFile();

    console.log('✅ Secret management initialized');
  }

  async loadEnvFile() {
    try {
      const envConfig = dotenv.config({ path: this.envPath });
      if (envConfig.parsed) {
        this.config = { ...this.config, ...envConfig.parsed };
        console.log('📄 Loaded existing .env file');
      }
    } catch (error) {
      console.log('📝 No existing .env file found, creating new one');
    }
  }

  async ensureSecretsDirectory() {
    try {
      await fs.mkdir(this.secretsDir, { recursive: true, mode: 0o700 });
      console.log('📁 Secrets directory ready');
    } catch (error) {
      if (error.code !== 'EEXIST') {
        throw error;
      }
    }
  }

  async validateAndGenerateSecrets() {
    const requiredSecrets = {
      // Migration & Security
      MIGRATION_ENCRYPTION_KEY: this.generateEncryptionKey(),
      MASTER_ENCRYPTION_KEY: this.generateEncryptionKey(),
      BACKUP_ENCRYPTION_KEY: this.generateEncryptionKey(),

      // Wallet
      WALLET_ADDRESS: this.config.WALLET_ADDRESS || '',
      SOLANA_RPC_URL: this.config.SOLANA_RPC_URL || 'https://api.mainnet.solana.com',

      // API Keys
      ANIDAY_API_KEY: this.config.ANIDAY_API_KEY || '',
      DIFY_API_KEY: this.config.DIFY_API_KEY || '',
      N8N_API_KEY: this.config.N8N_API_KEY || '',
      N8N_WEBHOOK_URL: this.config.N8N_WEBHOOK_URL || '',

      // Cloud Providers
      DIGITALOCEAN_ACCESS_TOKEN: this.config.DIGITALOCEAN_ACCESS_TOKEN || '',
      LINODE_ACCESS_TOKEN: this.config.LINODE_ACCESS_TOKEN || '',
      VULTR_ACCESS_TOKEN: this.config.VULTR_ACCESS_TOKEN || '',
      AWS_ACCESS_KEY_ID: this.config.AWS_ACCESS_KEY_ID || '',
      AWS_SECRET_ACCESS_KEY: this.config.AWS_SECRET_ACCESS_KEY || '',
      CLOUDFLARE_TOKEN: this.config.CLOUDFLARE_TOKEN || '',
      VERCEL_TOKEN: this.config.VERCEL_TOKEN || '',

      // System
      NODE_ENV: this.config.NODE_ENV || 'production',
      NEXT_TELEMETRY_DISABLED: this.config.NEXT_TELEMETRY_DISABLED || '1',
      RATE_LIMIT_ENABLED: this.config.RATE_LIMIT_ENABLED || 'true'
    };

    // Generate or validate each secret
    for (const [key, defaultValue] of Object.entries(requiredSecrets)) {
      if (!this.config[key] && defaultValue) {
        this.config[key] = defaultValue;
        console.log(`🔑 Generated ${key}`);
      } else if (this.config[key]) {
        console.log(`✅ ${key} already configured`);
      }
    }

    // Create Docker secret files
    await this.createDockerSecrets();
  }

  generateEncryptionKey() {
    return crypto.randomBytes(32).toString('hex');
  }

  async createDockerSecrets() {
    const secretMappings = {
      'migration_encryption_key': 'MIGRATION_ENCRYPTION_KEY',
      'master_encryption_key': 'MASTER_ENCRYPTION_KEY',
      'backup_encryption_key': 'BACKUP_ENCRYPTION_KEY',
      'wallet_address': 'WALLET_ADDRESS',
      'solana_rpc_url': 'SOLANA_RPC_URL',
      'aniday_api_key': 'ANIDAY_API_KEY',
      'dify_api_key': 'DIFY_API_KEY',
      'n8n_api_key': 'N8N_API_KEY',
      'n8n_webhook_url': 'N8N_WEBHOOK_URL',
      'digitalocean_access_token': 'DIGITALOCEAN_ACCESS_TOKEN',
      'linode_access_token': 'LINODE_ACCESS_TOKEN',
      'vultr_access_token': 'VULTR_ACCESS_TOKEN',
      'aws_access_key_id': 'AWS_ACCESS_KEY_ID',
      'aws_secret_access_key': 'AWS_SECRET_ACCESS_KEY',
      'cloudflare_token': 'CLOUDFLARE_TOKEN',
      'vercel_token': 'VERCEL_TOKEN'
    };

    for (const [filename, envKey] of Object.entries(secretMappings)) {
      const secretPath = path.join(this.secretsDir, `${filename}.txt`);
      const value = this.config[envKey] || '';

      try {
        await fs.writeFile(secretPath, value, { mode: 0o600 });
      } catch (error) {
        console.error(`Failed to create secret ${filename}:`, error);
      }
    }

    console.log('🔒 Docker secrets created');
  }

  async createSafeEnvFile() {
    const envContent = `# OpenMind AI Environment Configuration
# Generated by secret management system
# DO NOT commit this file to version control

# System Configuration
NODE_ENV=${this.config.NODE_ENV}
NEXT_TELEMETRY_DISABLED=${this.config.NEXT_TELEMETRY_DISABLED}
RATE_LIMIT_ENABLED=${this.config.RATE_LIMIT_ENABLED}

# Wallet Configuration
WALLET_ADDRESS=${this.maskSecret(this.config.WALLET_ADDRESS)}
SOLANA_RPC_URL=${this.config.SOLANA_RPC_URL}

# API Keys (masked for security)
ANIDAY_API_KEY=${this.maskSecret(this.config.ANIDAY_API_KEY)}
DIFY_API_KEY=${this.maskSecret(this.config.DIFY_API_KEY)}
N8N_API_KEY=${this.maskSecret(this.config.N8N_API_KEY)}
N8N_WEBHOOK_URL=${this.maskSecret(this.config.N8N_WEBHOOK_URL)}

# Cloud Provider Tokens (masked for security)
DIGITALOCEAN_ACCESS_TOKEN=${this.maskSecret(this.config.DIGITALOCEAN_ACCESS_TOKEN)}
LINODE_ACCESS_TOKEN=${this.maskSecret(this.config.LINODE_ACCESS_TOKEN)}
VULTR_ACCESS_TOKEN=${this.maskSecret(this.config.VULTR_ACCESS_TOKEN)}
AWS_ACCESS_KEY_ID=${this.maskSecret(this.config.AWS_ACCESS_KEY_ID)}
AWS_SECRET_ACCESS_KEY=${this.maskSecret(this.config.AWS_SECRET_ACCESS_KEY)}
CLOUDFLARE_TOKEN=${this.maskSecret(this.config.CLOUDFLARE_TOKEN)}
VERCEL_TOKEN=${this.maskSecret(this.config.VERCEL_TOKEN)}

# Encryption Keys (masked for security)
MIGRATION_ENCRYPTION_KEY=${this.maskSecret(this.config.MIGRATION_ENCRYPTION_KEY)}
MASTER_ENCRYPTION_KEY=${this.maskSecret(this.config.MASTER_ENCRYPTION_KEY)}
BACKUP_ENCRYPTION_KEY=${this.maskSecret(this.config.BACKUP_ENCRYPTION_KEY)}

# Redis (if used)
# REDIS_URL=redis://localhost:6379
`;

    await fs.writeFile(this.envPath, envContent);
    console.log('📝 Created .env file with masked secrets');
  }

  maskSecret(value) {
    if (!value || value.length < 8) return value || '';
    return value.substring(0, 4) + '*'.repeat(Math.max(0, value.length - 8)) + value.substring(value.length - 4);
  }

  async validateSecrets() {
    const issues = [];

    // Check for weak encryption keys
    const encryptionKeys = ['MIGRATION_ENCRYPTION_KEY', 'MASTER_ENCRYPTION_KEY', 'BACKUP_ENCRYPTION_KEY'];
    for (const key of encryptionKeys) {
      if (this.config[key] && this.config[key].length < 32) {
        issues.push(`Weak ${key}: should be at least 32 characters`);
      }
    }

    // Check for missing critical secrets
    const criticalSecrets = ['MIGRATION_ENCRYPTION_KEY', 'MASTER_ENCRYPTION_KEY'];
    for (const key of criticalSecrets) {
      if (!this.config[key]) {
        issues.push(`Missing critical secret: ${key}`);
      }
    }

    if (issues.length > 0) {
      console.log('⚠️  Secret validation issues:');
      issues.forEach(issue => console.log(`   - ${issue}`));
    } else {
      console.log('✅ All secrets validated');
    }

    return issues;
  }

  getConfig() {
    return { ...this.config };
  }

  async rotateKey(keyName) {
    if (!['MIGRATION_ENCRYPTION_KEY', 'MASTER_ENCRYPTION_KEY', 'BACKUP_ENCRYPTION_KEY'].includes(keyName)) {
      throw new Error(`Cannot rotate key: ${keyName}`);
    }

    const newKey = this.generateEncryptionKey();
    this.config[keyName] = newKey;

    await this.createDockerSecrets();
    await this.createSafeEnvFile();

    console.log(`🔄 Rotated ${keyName}`);
    return newKey;
  }
}

// CLI Interface
async function main() {
  const secretManager = new SecretManager();
  const command = process.argv[2];

  try {
    switch (command) {
      case 'init':
      case 'setup':
        await secretManager.initialize();
        break;

      case 'validate':
        await secretManager.loadEnvFile();
        await secretManager.validateSecrets();
        break;

      case 'rotate':
        const keyToRotate = process.argv[3];
        if (!keyToRotate) {
          console.error('Usage: node setup-secrets.js rotate <key_name>');
          process.exit(1);
        }
        await secretManager.loadEnvFile();
        const newKey = await secretManager.rotateKey(keyToRotate);
        console.log(`New ${keyToRotate}: ${newKey}`);
        break;

      case 'status':
        await secretManager.loadEnvFile();
        console.log('🔍 Secret Status:');
        Object.keys(secretManager.getConfig()).forEach(key => {
          const masked = secretManager.maskSecret(secretManager.getConfig()[key]);
          console.log(`   ${key}: ${masked ? 'set' : 'not set'}`);
        });
        break;

      default:
        console.log('OpenMind AI Secret Management');
        console.log('Usage:');
        console.log('  node setup-secrets.js init     # Initialize secrets');
        console.log('  node setup-secrets.js validate # Validate secrets');
        console.log('  node setup-secrets.js status   # Show secret status');
        console.log('  node setup-secrets.js rotate <key> # Rotate encryption key');
        process.exit(1);
    }

  } catch (error) {
    console.error('❌ Secret management error:', error);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = SecretManager;